#!/bin/bash
rm -f DIRTYPCB.ZIP
cp *-F_Cu.gbr TOP_COPPER.GTL
cp *-B_Cu.gbr BTM_COPPER.GBL
cp *-F_Mask.gbr TOP_MASK.GTS
cp *-B_Mask.gbr BTM_MASK.GBS
cp *-F_SilkS.gbr TOP_SILK.GTO
cp *-B_SilkS.gbr BTM_SILK.GBO
cp *-Edge_Cuts.gbr BRD_EDGE.GBR
cp *.drl BRD_DRILL.TXT
zip -m DIRTYPCB.ZIP TOP_COPPER.GTL BTM_COPPER.GBL TOP_MASK.GTS BTM_MASK.GBS TOP_SILK.GTO BTM_SILK.GBO BRD_EDGE.GBR BRD_DRILL.TXT
